### ISSUE TITLE
Ignore key

### ISSUE THREAD

**Issue by uyab** [javanlabs/rt-report#25]
Daftar key dipindahkan ke file config atau semacam environment variable, dan ditambahkan ke gitignore, sehingga tidak terekspos ke publik.

**Comment by purwadarozatun** [comment]
Knapa gak di simpan di database aja skalian mas 
jadinya server buat data pegawai gt diasana bisa di buat nyimpen kaya data data nama , recuetime_key ,  about , gambar  , skil skill yang pegawai punya dll

**Comment by adhatama** [comment]
about, gambar, dan skills menurutku ndak terlalu relevan.
kalo buat nyimpen nama dan key aja cukup di file config for simplicity. Dibanding dari db yang harus setup macem-macem.

**Comment by purwadarozatun** [comment]
Hmmm iya sih yowes tak bikin dah

**Comment by uyab** [comment]
Mungkin ga kalau ini bentuknya json?

Jadi formatnya semacam kayak gini:

``` javascript
[
{name:"Purwa", rescueTimeKey:"1234"},
{name:"Tama", rescueTimeKey:"897"}
]
```

**Comment by purwadarozatun** [comment]
iya bisa mas nanti aku bikin people.json isinya json itu

**Comment by purwadarozatun** [comment]
closed di 84532600d1a3c2cad9ff24441fc7b94cfba53a0a
