### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by uyab** [javanlabs/rt-report#27]
**Story**
Sebagai supervisor, saya bisa melihat peringkat productivity score dari seluruh tim dalam bulan tertentu.

**Acceptance Criteria**
1. Ada filter bulan dan tahun, default to bulan dan tahun sekarang.
2. Hasil report ditampilkan terurut productivity score yang paling besar
3. Bisa export ke excel dengan format nama file `januari-2016-productivity-score.xls`

**Sample Output**

| Player | Total Logged Time | Average Daily Logged Time | Productivity Score |
| --- | --- | --- | --- |
| Rayhan | 38h 10m | 6h 50m | 77% |
| Akbar | 34h 10m | 6h 1m | 71% |

**Comment by purwadarozatun** [comment]
yang ini berarti harus nyimpen ke database brarti . soalnya dari rescuetime nya gak ada.

aku kmaren baca baca ternyata ada namanya node cron http://www.codexpedia.com/javascript/nodejs-cron-schedule-examples/
tinggal datanya mau di grab per end of day atau setiap jam mas ?
